### ISSUE TITLE
PostExcerpt & error in section 'Displaying Loading State'

### ISSUE THREAD

**Issue by klequis** [markerikson/redux-quickstart-example-app#1]
Hi. Haven't updated my way of doing Redux in years. Was going through your tutorial to do so. Very much liking retux-toolkit!

Noticed in Displaying Loading State you introduce the variable `error` and the component `<PostExcerpt />`. I didn't find either in any of the projects branches. Was able to fill those in myself. Don't know if this is part of your focusing on the main points and not intending to be code complete or if the project & tutorial are a work in progress.

Either way, thanks for another great tutorial! (I've been over most of your blog in the past.) I'm happy to post what I find along the way, do review for you (if it isn't complete) and/or contribute code.

**Comment by markerikson** [comment]
It's entirely possible (even likely) that I have a couple typos in the code snippets :)  If you can point to where there's discrepancies between the code snippets and the repo commits, let me know.  (Also feel free to submit a PR to fix the docs to match the repo code.)

**Comment by Kruglyanski** [comment]
> Hi. Haven't updated my way of doing Redux in years. Was going through your tutorial to do so. Very much liking retux-toolkit!
> 
> Noticed in Displaying Loading State you introduce the variable `error` and the component `<PostExcerpt />`. I didn't find either in any of the projects branches. Was able to fill those in myself. Don't know if this is part of your focusing on the main points and not intending to be code complete or if the project & tutorial are a work in progress.
> 
> Either way, thanks for another great tutorial! (I've been over most of your blog in the past.) I'm happy to post what I find along the way, do review for you (if it isn't complete) and/or contribute code.

You can find PostExcerpt in the PostList.jsx file 
![image](https://user-images.githubusercontent.com/45219732/116353001-bbd8a000-a7fe-11eb-8c44-c3d423845c5b.png)
But in the tutorial I was confused too)

**Comment by markerikson** [comment]
Should be resolved by https://github.com/reduxjs/redux/pull/4153
