### ISSUE TITLE
Error handling in 'postsSlice.js'

### ISSUE THREAD

**Issue by weiranfu** [markerikson/redux-quickstart-example-app#2]
Thanks for writing this great tutorial especially for people like me to learn redux for the first time!
When I go through the code in `postsSlice.js`, I am wondering that maybe there's a small mistake about handling error for `fetchPosts` action.
In the `extraReducers` in `postsSlice.js`, when `[fetchPosts.rejected]`, 
we will update the `state.error` to `state.error = action.error.message`.

However, when I check the redux-toolkit docs, I find that 
"if the promise failed and was not handled with `rejectWithValue`, dispatch the rejected action with a serialized version of the error value as `action.error`"
So maybe we should update the `state.error` to `state.error = action.error`?

I just start learning redux-toolkit and I probably not correctly understand the code. So if I am wrong please feel free to correct me.
Lastly, thanks a lot for your contribution to write this wonderful tutorial and it helps a lot to learn redux.

**Comment by markerikson** [comment]
Yeah, I think I've probably got that example wrong, actually.  I need to update it.  Appreciate the notice!
