### ISSUE TITLE
Checkpoints 5 and 6 render posts as `[object Object]` in CodeSandbox

### ISSUE THREAD

**Issue by adamerose** [markerikson/redux-quickstart-example-app#22]
https://codesandbox.io/s/github/reduxjs/redux-essentials-example-app/tree/checkpoint-5-createApi
https://codesandbox.io/s/github/reduxjs/redux-essentials-example-app/tree/checkpoint-6-rtkqConversion

![image](https://user-images.githubusercontent.com/10884874/142780944-8a11f48e-10dc-4e90-87d8-f45c26cf51a3.png)

Doesn't happen locally, only in CodeSanbox

**Comment by markerikson** [comment]
This is probably due to the known issue where the MSW mock API setup needs to be adjusted - the code currently doesn't wait for that to start up properly before rendering the app.  Haven't had time to go back and rewrite the example commits to fix that.

**Comment by markerikson** [comment]
Should be fixed now!
