### ISSUE TITLE
Add a version with TypeScript?

### ISSUE THREAD

**Issue by adamerose** [markerikson/redux-quickstart-example-app#23]
I see a few small TypeScript examples linked from the [docs](https://redux.js.org/usage/usage-with-typescript#resources) but it says they go against recommended practices and I think they aren't as extensive as this example app. If I added TypeScript to this project, would it be useful if I submitted a PR to add it as an example for the docs?

**Comment by markerikson** [comment]
Our primary TS examples are:

- The "TS Quick Start" page: https://redux.js.org/tutorials/typescript-quick-start
- The larger "TS Usage Guide" page: https://redux.js.org/usage/usage-with-typescript
- The more specific "TS Usage" pages in the RTK docs: https://redux-toolkit.js.org/usage/usage-with-typescript , https://redux-toolkit.js.org/rtk-query/usage-with-typescript

I agree it would be nice to have TS covered in the "Essentials" tutorial as well, but its main goal is to teach the concepts and the mechanics of using Redux, and adding TS to that as well would complicate things.

**Comment by adamerose** [comment]
> its main goal is to teach the concepts and the mechanics of using Redux, and adding TS to that as well would complicate things.

Ah yeah that makes sense. Thanks for the links and quick reply :)
