### ISSUE TITLE
where is the postsSlice file

### ISSUE THREAD

**Issue by Johnnycapreano** [markerikson/redux-quickstart-example-app#28]
i was following the redux-essentials-tutorial i have reached the Redux Essentials, Part 5: Async Logic and Data Fetching there is a PostsSlice  File in the example code i have downloaded the redux projectFiles  regarding that section which was provided  but There is no PostsSlice File in the repo because of That i cant follow up with the tutorial
![2022-02-14 11-03-02](https://user-images.githubusercontent.com/74734400/153832764-86953a6d-66b1-4167-a3db-658a8e5cf4d2.png)

**Comment by markerikson** [comment]
The `master` branch only has the basic application setup. All the application code is on the `tutorial-steps` branch - you'll need to check that out instead.

You can see the final branch contents here:

- https://github.com/reduxjs/redux-essentials-example-app/tree/tutorial-steps

And the code at the end of Part 4 is here:

- https://github.com/reduxjs/redux-essentials-example-app/tree/checkpoint-2-reactionButtons
