### ISSUE TITLE
Error installing dependencies

### ISSUE THREAD

**Issue by codigoisaac** [markerikson/redux-quickstart-example-app#29]
When running either `yarn install` or `npm install` I get errors.

With npm: 

`$ npm install
npm ERR! code ERR_SOCKET_TIMEOUT
npm ERR! errno ERR_SOCKET_TIMEOUT
npm ERR! network Invalid response body while trying to fetch https://registry.npmjs.org/react-router: Socket timeout
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.`

yarn.error.log:

`Trace: 
  Error: https://registry.yarnpkg.com/date-fns/-/date-fns-2.28.0.tgz: ESOCKETTIMEDOUT` ...

**Comment by markerikson** [comment]
Afraid this has nothing to do with the repo itself - this is an issue between your computer and the NPM servers.

**Comment by codigoisaac** [comment]
> Afraid this has nothing to do with the repo itself - this is an issue between your computer and the NPM servers.

It looks like it had something to do with the 'date-fns' dependency version. I installed it separately with the latest version and all worked fine.

**Comment by markerikson** [comment]
I honestly don't think it has anything to do with any particular dependency version :)

If you look at the original error, it was a "socket timeout" error, while trying to download `react-router` (and later `date-fns`)

That means your computer just literally couldn't establish a connection to the NPM registry servers.

Things must have worked okay this time around.
