### ISSUE TITLE
Error with command: npm install

### ISSUE THREAD

**Issue by mohamedmehdigara** [markerikson/redux-quickstart-example-app#34]
PS C:\Users\p-c\Downloads\Github\redux-essentials-example-app> npm install
npm ERR! code ERR_SOCKET_TIMEOUT 
npm ERR! network Invalid response body while trying to fetch https://registry.npmjs.org/@typescript-eslint%2fexperimental-utils: Socket timeout
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\p-c\AppData\Local\npm-cache\_logs\2022-05-29T16_32_32_683Z-debug-0.log    
PS C:\Users\p-c\Downloads\Github\redux-essentials-example-app> npm install --legacy-peer-deps   
npm ERR! code ERR_SOCKET_TIMEOUT
npm ERR! errno ERR_SOCKET_TIMEOUT
npm ERR! network Invalid response body while trying to fetch https://registry.npmjs.org/@typescript-eslint%2fexperimental-utils: Socket timeout
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\p-c\AppData\Local\npm-cache\_logs\2022-05-29T16_39_29_873Z-debug-0.log

**Comment by markerikson** [comment]
Per the error message, `npm` on your computer is having trouble trying to connect to the NPM package registry, so this is an issue just on your computer.
