### ISSUE TITLE
SinglePost page needs fecthing too

### ISSUE THREAD

**Issue by ghost** [markerikson/redux-quickstart-example-app#4]
I was building my own app using this essential and faced with this, so basically when we on SinglePost page and try to re-render the page it reloads and returns us nothing because there is no fetching data and inserting in redux store in the component, i think this is a mistake if not how to handle this?

**Comment by markerikson** [comment]
Yeah, it's something you may want to consider doing for yourself.  As the start of the tutorial said, this isn't a complete production-ready app - the goal was to illustrate specific Redux concepts and APIs, and I didn't try to cover every single case.
