### ISSUE TITLE
When compiling the project can't resolve the file immer.cjs.development.js

### ISSUE THREAD

**Issue by memowii** [markerikson/redux-quickstart-example-app#6]
![image](https://user-images.githubusercontent.com/5409172/96654662-6f695080-1301-11eb-9635-d637a2dfccbb.png)

I'm following the redux  tutorial from the their docs, and when I start the project it always shows that error. Can you help me with this issue?

**Comment by markerikson** [comment]
Immer put out a bad release today.  Should hopefully be fixed now:

https://github.com/immerjs/immer/releases/tag/v7.0.14

https://github.com/immerjs/immer/issues/685
