### ISSUE TITLE
[Bug] Browser reload drops state updates

### ISSUE THREAD

**Issue by SomervilleTom** [markerikson/redux-quickstart-example-app#65]
This issue appears to be similar to [Issue #64](https://github.com/reduxjs/redux-essentials-example-app/issues/64).

I'm using the `tutorial-steps` branch of the tutorial, and I exercised the app immediately after adding `SinglePostPage`.

I had to make several modifications to 'package.json' in order to make the app run, as follows:

1. Update the `msw` to require "^0.38.0"
2. Update `react-scripts` to require "^5"
3. Run "git reset --hard 4ee39fb" in the project directory. 
4. After 'yarn install`, copy a patched 'getHttpsConfig.js' into `react-scripts/config/`
5. After `yarn install`, run 'npx msw init public' from the project directory
 
With these changes in place, I think performed the tutorial steps to:
1. Add `SinglePostPage`
2. Update `App.js` as per the tutorial
3. Update `PostsList.js` as per the tutorial
4. Update `Navbar.js` as per the tutorial
5. Run the tutorial and add a post using "Save Page"

The third post appears in the app:

![single_post_page_before_reload](https://github.com/reduxjs/redux-essentials-example-app/assets/64976799/3d1334be-54d3-47e0-99ec-f7ea545aa6d2)

I then clicked reload in the (Chrome) browser. This causes the added post to be dropped:

![single_post_page_after_reload](https://github.com/reduxjs/redux-essentials-example-app/assets/64976799/00ffc85d-0d37-45a5-840c-bf51226826d0)

I see similar behavior in `PostsList'. Immediately after clicking "Save Post", I see the added post:

![posts_page_before_reload](https://github.com/reduxjs/redux-essentials-example-app/assets/64976799/f599b50f-1a5b-40e8-bac9-e7695317b2b3)

After reload, the added post disappears:

![posts_page_after_reload](https://github.com/reduxjs/redux-essentials-example-app/assets/64976799/288c57ef-896d-4be2-9fee-75a863a6a7bb)

I used breakpoints in the `dispatch` call to `postAdded` in `SinglePostForm` and `postsSlice`, and it appears that the value of `state` -- presumably coming from `Provider` -- is reset to its initial state after a refresh.

Sadly, I don't have the expertise to determine whether this is a bug in the tutorial, in `@reduxjs/toolkit`, or in redux itself.

I appreciate any guidance or workaround for ensuring that the app I'm building will behave as expected after a reload.

**Comment by markerikson** [comment]
Hi! Sorry for the _very_ late response. I'm finally doing some updates on the example app and saw this.

This is expected behavior. A Redux store is like any other JS variable - it only exists for the lifetime of this page.  When you reload the page, an entire new JS environment is created from scratch, including a _new_ Redux store.

This example app is configured to generate some initial fake data, but it doesn't do anything to _persist_ items you might have added while using the example app.

So yes, reloading the page _will_ throw away all of the new items you added - that's fully expected.
