### ISSUE TITLE
posts.map() is not a function

### ISSUE THREAD

**Issue by Op-Pautu** [markerikson/redux-quickstart-example-app#70]
import { configureStore } from '@reduxjs/toolkit'

export const store = configureStore({
  reducer: () => ({}),
})

changing the above to this fixes it (but why):
export const store = configureStore({
  reducer: {
    posts: postsReducer,
  },
})

**Comment by markerikson** [comment]
Because the first example has an _empty_ store with no actual reducer state at all - just an empty object.

The second example defines `state.posts`, handled by `postsReducer`.
